don't double-prepend Error: to messages
before:

$ hp -b pkgdiff
Checking if any dependency-infos need to be updated ...
Looking for stale dependency-infos ...
Warning: skipping pkgdiff-1.7.2, as the recipe is broken
Error: Error: SUMMARY must start with a capital letter (/boot/home/haikuports/dev-util/pkgdiff/pkgdiff-1.7.2.recipe).
Error: No version of pkgdiff can be built

after:

$ hp -b pkgdiff
Checking if any dependency-infos need to be updated ...
Looking for stale dependency-infos ...
Warning: skipping pkgdiff-1.7.2, as the recipe is broken
Error: SUMMARY must start with a capital letter (/boot/home/haikuports/dev-util/pkgdiff/pkgdiff-1.7.2.recipe).
Error: No version of pkgdiff can be built